<?php
/**
 * @file
 * CI Badge
 */

/**
 * Implements hook_menu().
 */
function islandora_ci_badge_menu() {
  return array(
    'admin/islandora/tools/badges/ci_badge' => array(
      'title' => 'Cultural Institution Badge',
      'description' => 'CI Badge settings.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_ci_badge_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function islandora_ci_badge_block_info() {
  return array(
    'islandora_ci_badge_attribution' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'info' => t('Islandora CI Badge'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function islandora_ci_badge_block_view($delta = '') {
  module_load_include('inc', 'islandora_badges', 'includes/utilities');
  module_load_include('inc', 'islandora_ci_badge', 'includes/utilities');
  $to_render = array();
  if ($delta == 'islandora_ci_badge_attribution') {
    $object = menu_get_object('islandora_object', 2);
    if ($object) {
      // Check CModel against Badges configuration.
      if (islandora_badges_show_for_cmodel($object)) {
        $attribution = islandora_ci_badge_get_attribution_notice($object);
        if (!isset($attribution)) {
          return;
        }
        $ci_badge = islandora_ci_badge_html($attribution);
        $to_render['content'] = $ci_badge;
      }
    }
  }
  return $to_render;
}
